[[main]]
  identifier = "programa"
  name = "Programa"
  url = "programa"
  weight = 1

[[main]]
  identifier = "cronograma"
  name = "Cronograma"
  url = "cronograma"
  weight = 2

[[main]]
  identifier = "noticias"
  name = "Notícias"
  url = "noticias"
  weight = 3

[[main]]
  identifier = "contato"
  name = "Contato"
  url = "contato"
  weight = 4