baseURL = "https://ericbrasiln.github.io"
title = "CCLHM0057 História da América: coloniação e resistência, 2020.2"
theme = "zdoc"
description = "Site do curso CCLHM0057 - História da América: coloniação e resistência, 2020.2 (IHL,UNILAB)"
